theme: jekyll-theme-cayman

title: PhotoDemon automatic update interface
tagline: the official automatic update server for PhotoDemon 7.2+
locale: "en"
author:
   name: Tanner Helland
   url: https://photodemon.org

pd-stable-v: 2025.12.0.0
pd-beta-v: 2025.12.0.0
pd-nightly-v: 2025.12.0.34

